##############################################################################
#  Filebeat configuration to ingest access logs from the blog website.       #
#  The data is already in in JSON format and does not need any processing.   #
#  Extract the blog_access_logs.tar.gz file and set paths correctly          #
##############################################################################

filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.csv

output.logstash:
  hosts: ["logstash:5044"]
